### ISSUE TITLE
Update HUB API requests

### ISSUE THREAD

**Issue by Burhan-Q** [Burhan-Q/Ultralytics_DiscordBot#48]
After release of latest HUB API, bot inference requests no longer working
- [ ] use new format
- [ ] investigate account link authorization
- [ ] test adding new tasks

**Comment by Burhan-Q** [comment]
NOTES HUB API requests:

[Ultralytics HUB Documentation reference](https://docs.ultralytics.com/hub/inference_api/)

- `f"https://api.ultralytics.com/v1/predict/{MODEL_ID}"` is the new end point
    - this means users _could_ pass in their own trained model
    - otherwise, need to use default model-id for the pretrained models (includes tasks besides detection)

- all inference arguments are passed into `data` keyword as a dictionary
    - `conf` : prediction confidence
    - `size` : prediction image size
    - `iou` : prediction iou threshold
    - `url` : image URL
    - `normalize`
> [!NOTE]
Image URL can be passed directly to inference API

- HUB account API key is required as part of the headers
    - `headers = {"x-api-key": f"API_KEY"}`
    - would be preferred if there was a means to obtain a key with zero intervention from the bot (linked/connected account) but the Discord docs don't make it obvious how to accomplish this (to me) 
    
- inference results returned as part of `.json()` method of response
    - for `detect` results, response is:
 
```yaml
{data: [
  {
    class: int,
    confidence: float,
    name: str,
    width: float,
    height: float,
    xcenter: float,
    ycenter: float,
  }, 
  {...}, # additional objects detected
]
```
